FROM debian:bookworm-slim



ARG SRC="/home/jupyter/local"
ARG USR="jupyter"



RUN apt-get upgrade



RUN apt-get update && apt-get install -y \
    apt-utils \
    curl wget \
    gzip unzip tar \
    ca-certificates \
    build-essential \
    git \
    psmisc procps \
    locales \
    libssl-dev \
    zlib1g-dev \
    libncurses5-dev \
    libncursesw5-dev \
    libreadline-dev \
    libsqlite3-dev \
    libgdbm-dev \
    libdb5.3-dev \
    libbz2-dev \
    libexpat1-dev \
    liblzma-dev \
    tk-dev \
    libyaml-dev \
    libzmq3-dev \
    bash \
    cargo \
    make \
    cmake \
    g++ \ 
    pkg-config \
    libssl-dev \
    lsb-release  \
    curl \
    software-properties-common \ 
    gnupg \
    sudo \
    ;


# Agrega snapshot deshabilitando verificación de GPG y expiración
RUN echo 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99no-check-valid-until && \
    echo 'Acquire::AllowInsecureRepositories "true";' >> /etc/apt/apt.conf.d/99no-check-valid-until && \
    echo 'deb [trusted=yes] http://snapshot.debian.org/archive/debian/20210601T000000Z bullseye main' > /etc/apt/sources.list.d/llvm11.list && \
    apt-get update && \
    apt-get install -y llvm-11 clang-11 libclang-11-dev && \
    rm /etc/apt/sources.list.d/llvm11.list && \
    rm /etc/apt/apt.conf.d/99no-check-valid-until && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

RUN useradd -m -s /bin/bash  ${USR} 
#    && echo "${USR}:qwerty" | chpasswd \
#    && usermod -aG sudo ${USR}











RUN mkdir -p ${SRC}

WORKDIR ${SRC}

###################### start python #########################################################



ARG PYTHON_VERSION=3.11.1

RUN cd ${SRC} \
    && wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz \
    && tar xzf Python-${PYTHON_VERSION}.tgz

RUN mkdir ${SRC}/python

# build python and remove left-over sources
RUN cd ${SRC}/Python-${PYTHON_VERSION} \
    && ./configure --prefix=${SRC}/python   --enable-loadable-sqlite-extensions \
    && cd ${SRC}/Python-${PYTHON_VERSION} && make && make install \
    && rm ${SRC}/Python-${PYTHON_VERSION}.tgz

RUN ln -s ${SRC}/python/bin/python3.11 ${SRC}/python/bin/python;


ENV PATH="$PATH:${SRC}/python/bin"

RUN pip3.11 install ipython
RUN pip3.11 install jupyter
RUN pip3.11 install numpy
RUN pip3.11 install matplotlib
RUN pip3.11 install bokeh
RUN pip3.11 install plotly
RUN pip3.11 install pandas
RUN pip3.11 install scipy
RUN pip3.11 install injector
RUN pip3.11 install pyzmq


#################### end python #############################################################

##################### start golang ##########################################################
ARG GOLANG_VERSION=1.21.0

RUN cd ${SRC} &&  wget https://go.dev/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz && \
    tar -xzvf go${GOLANG_VERSION}.linux-amd64.tar.gz

RUN rm -rf ${SRC}/go${GOLANG_VERSION}.linux-amd64.tar.gz

ENV  PATH=$PATH:${SRC}/go/bin
ENV GOPATH=${SRC}/go

RUN   go install github.com/gopherdata/gophernotes@v0.7.5


RUN mkdir -p  ${HOME}/.local/share/jupyter/kernels/gophernotes
RUN cp $(go env GOPATH)/pkg/mod/github.com/gopherdata/gophernotes@v0.7.5/kernel/* ${HOME}/.local/share/jupyter/kernels/gophernotes/;
RUN chmod 766  ${HOME}/.local/share/jupyter/kernels/gophernotes/*
RUN cd ${HOME}/.local/share/jupyter/kernels/gophernotes &&  sed "s|gophernotes|$(go env GOPATH)/bin/gophernotes|" < kernel.json.in > kernel.json;

##################### end golang ##########################################################

##################### start ruby ##########################################################

#no son las mismas versiones la que quedan en el contenedor

ARG LANG=C.UTF-8
ARG RUBY_MAJOR=3.3
ARG RUBY_VERSION=3.3.5

RUN cd ${SRC} &&  wget "https://cache.ruby-lang.org/pub/ruby/${RUBY_MAJOR}/ruby-${RUBY_VERSION}.tar.gz"

RUN cd ${SRC} && tar xzvf ruby-${RUBY_VERSION}.tar.gz
RUN cd ${SRC} && rm -rf ruby-${RUBY_VERSION}.tar.gz

RUN cd ${SRC}/ruby-${RUBY_VERSION} && ./configure  --prefix=${SRC}/ruby  && make && make install ;

RUN rm -rf ${SRC}/ruby-${RUBY_VERSION}

ENV PATH=$PATH:${SRC}/ruby/bin



RUN gem install rake
RUN gem install ffi
RUN gem install ffi-rzmq
RUN gem install iruby



##################### end ruby ##########################################################

###################### start erlang #####################################################

ARG ERLANG_OTP=25.0


#  https://github.com/erlang/otp/archive/refs/tags/OTP-${ERLANG_OTP}.tar.gz
RUN wget https://github.com/erlang/otp/releases/download/OTP-${ERLANG_OTP}/otp_src_${ERLANG_OTP}.tar.gz

RUN tar xzvf otp_src_${ERLANG_OTP}.tar.gz;

RUN mkdir -p ${SRC}/erlang

RUN  mv  otp_src_${ERLANG_OTP} ${SRC}/erlang


RUN cd  ${SRC}/erlang/otp_src_${ERLANG_OTP}  && \
    ./configure  --without-javac --disable-hipe --enable-builtin-zlib --without-odbc --without-wx --prefix=${SRC}/erlang &&\
    make clean && \
    make -j$(nproc) && \
    make install ;


ENV PATH=$PATH:${SRC}/erlang/bin

###################### end erlang #####################################################

#################### start elixir ########################################################
# vesiones de elixir otp
# https://builds.hex.pm/builds/elixir/builds.txt


ARG ELIXIR_VERSION=1.17.0
#ARG OTP_VERSION=25

RUN cd ${SRC}  &&  wget  https://github.com/elixir-lang/elixir/archive/refs/tags/v${ELIXIR_VERSION}.tar.gz && \
    tar xzvf  v${ELIXIR_VERSION}.tar.gz && \
    mv "elixir-$ELIXIR_VERSION"  elixir && \
    cd elixir && \
    make && \
    make install PREFIX="${SRC}/elixir" \
    ;

ENV PATH=$PATH:${SRC}/elixir/bin


#RUN git clone --depth 1 https://github.com/pprzetacznik/IElixir.git && \
#    cd IElixir && \
#    sed -i '/sqlite_ecto2/d' mix.exs  && \
#    rm -f lib/ielixir/repo.ex && \ 
#    rm -f lib/ielixir/queries.ex && \
#    rm -f lib/ielixir/history_entry.ex && \
#    sed -i 's/:ecto, *//' mix.exs && \
#    sed -i '/worker(IElixir\.Repo, \[\]),/d' lib/ielixir/supervisor.ex && \
#    mix local.hex --force && \
#    mix local.rebar --force  && \
#    mix deps.get          && \
#    mix deps.compile  && \
#    MIX_ENV=prod mix compile && \
#    chmod u+x ./install_script.sh && \
#   ./install_script.sh;



#RUN  mix --version;


#RUN mix test;



#################### end elixir ########################################################

######################## start c/c++ ################################################### 


RUN export CC=clang-14
RUN export CXX=clang++-14


RUN wget https://apt.llvm.org/llvm.sh && \
    chmod +x llvm.sh && \
    ./llvm.sh 14;


RUN  cd ${SRC}  &&git clone --branch v0.9 https://github.com/root-project/cling.git && \
    cd cling && \
    mkdir build && cd build && \
    cmake -DCMAKE_INSTALL_PREFIX=${SRC}/cling && \
    make -j$(nproc) && \
    make install ;

ENV PATH=${PATH}:${SRC}/cling/bin

RUN  cd ${SRC}  && git clone https://github.com/jupyter-xeus/xeus-cling.git && \
    cd xeus-cling && \
    mkdir build && cd build && \
    cmake .. -DCMAKE_INSTALL_PREFIX=${SRC}/xeus-cling && \
    make -j$(nproc) && make install &&

ENV  PATH=${PATH}:${SRC}/xeus-cling/bin


RUN    jupyter kernelspec install ${SRC}/xeus-cling/share/jupyter/kernels/xcpp11 --user



######################## end c/c++ ###################################################


###################### init jupyter ####################################################

RUN iruby register --force;

#RUN jupyter kernel --kernel=ielixir;


###################### end jupyter ######################################################


EXPOSE 8888



#COPY entrypoint.sh /

#ENTRYPOINT [ "/entrypoint.sh" ]

CMD jupyter lab --ip 0.0.0.0 --no-browser --NotebookApp.token='' --NotebookApp.password='' --notebook-dir="$HOME/note"
