FROM debian:12-slim

ARG SRC="/home/jupyter/local"
ARG USR="jupyter"

# Install base dependencies
RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    apt-utils \
    curl wget \
    gzip unzip tar \
    ca-certificates \
    build-essential \
    git \
    psmisc procps \
    locales \
    libssl-dev \
    zlib1g-dev \
    libncurses5-dev \
    libncursesw5-dev \
    libreadline-dev \
    libsqlite3-dev \
    libgdbm-dev \
    libdb5.3-dev \
    libbz2-dev \
    libexpat1-dev \
    liblzma-dev \
    libgmp-dev \
    tk-dev \
    libyaml-dev \
    libzmq3-dev \
    bash \
    sudo \
    cmake \
    pkg-config \
    nodejs \
    npm \
    && rm -rf /var/lib/apt/lists/*

# User setup
RUN useradd -m -s /bin/bash ${USR}
USER ${USR}
RUN mkdir -p ${SRC}
WORKDIR ${SRC}

###################### start python #########################################################
# Python 3.13.1
ARG PYTHON_VERSION=3.13.1

RUN cd ${SRC} \
    && wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz \
    && tar xzf Python-${PYTHON_VERSION}.tgz

RUN mkdir ${SRC}/python

RUN cd ${SRC}/Python-${PYTHON_VERSION} \
    && ./configure --prefix=${SRC}/python --enable-loadable-sqlite-extensions --enable-optimizations \
    && make -j$(nproc) && make install \
    && rm -rf ${SRC}/Python-${PYTHON_VERSION} ${SRC}/Python-${PYTHON_VERSION}.tgz

RUN ln -s ${SRC}/python/bin/python3 ${SRC}/python/bin/python
ENV PATH="${SRC}/python/bin:${PATH}"

# Install Jupyter, LSP and libraries
# python-lsp-server[all] provides autocompletion for Python
RUN pip3 install --no-cache-dir --upgrade pip \
    && pip3 install --no-cache-dir ipython jupyterlab notebook jupyterlab-lsp jupyter-lsp 'python-lsp-server[all]' \
    && pip3 install --no-cache-dir numpy matplotlib bokeh plotly pandas scipy injector pyzmq bash_kernel ipywidgets ipympl mnemonic eth-account bip-utils

RUN python3 -m bash_kernel.install

#################### end python #############################################################

##################### start golang ##########################################################
# Go 1.23.4
ARG GOLANG_VERSION=1.23.4

RUN cd ${SRC} && wget https://go.dev/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz && \
    tar -xzvf go${GOLANG_VERSION}.linux-amd64.tar.gz && \
    rm go${GOLANG_VERSION}.linux-amd64.tar.gz

ENV PATH="${SRC}/go/bin:${PATH}"
ENV GOPATH="${SRC}/go-workspace"
ENV PATH="${GOPATH}/bin:${PATH}"

RUN go install github.com/gopherdata/gophernotes@v0.7.5
# gopls provides LSP support for Go
RUN go install golang.org/x/tools/gopls@latest

RUN mkdir -p ${HOME}/.local/share/jupyter/kernels/gophernotes
RUN cp $(go env GOPATH)/pkg/mod/github.com/gopherdata/gophernotes@v0.7.5/kernel/* ${HOME}/.local/share/jupyter/kernels/gophernotes/;
RUN chmod 766 ${HOME}/.local/share/jupyter/kernels/gophernotes/*
RUN cd ${HOME}/.local/share/jupyter/kernels/gophernotes && sed "s|gophernotes|$(go env GOPATH)/bin/gophernotes|" < kernel.json.in > kernel.json;

##################### end golang ##########################################################

##################### start ruby ##########################################################
# Ruby 3.4.1
ARG RUBY_MAJOR=3.4
ARG RUBY_VERSION=3.4.1

RUN cd ${SRC} && wget "https://cache.ruby-lang.org/pub/ruby/${RUBY_MAJOR}/ruby-${RUBY_VERSION}.tar.gz" \
    && tar xzvf ruby-${RUBY_VERSION}.tar.gz \
    && rm ruby-${RUBY_VERSION}.tar.gz

RUN cd ${SRC}/ruby-${RUBY_VERSION} && ./configure --prefix=${SRC}/ruby && make -j$(nproc) && make install \
    && rm -rf ${SRC}/ruby-${RUBY_VERSION}

ENV PATH="${SRC}/ruby/bin:${PATH}"

# solargraph provides LSP support for Ruby
RUN gem install --no-document rake ffi ffi-rzmq iruby solargraph
RUN iruby register --force

##################### end ruby ##########################################################

##################### start rust ##########################################################
# Rust installation via rustup
ENV RUSTUP_HOME=${SRC}/rustup
ENV CARGO_HOME=${SRC}/cargo
ENV PATH="${CARGO_HOME}/bin:${PATH}"

RUN curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y --no-modify-path \
    && ${CARGO_HOME}/bin/rustup component add rust-analyzer

# Install evcxr (Rust Jupyter kernel)
RUN cargo install evcxr_jupyter \
    && evcxr_jupyter --install

##################### end rust ##########################################################

###################### start erlang #####################################################
# Erlang OTP 27.2
ARG ERLANG_OTP=27.2

RUN wget https://github.com/erlang/otp/releases/download/OTP-${ERLANG_OTP}/otp_src_${ERLANG_OTP}.tar.gz \
    && tar xzvf otp_src_${ERLANG_OTP}.tar.gz \
    && mkdir -p ${SRC}/erlang_build \
    && mv otp_src_${ERLANG_OTP} ${SRC}/erlang_build/

RUN cd ${SRC}/erlang_build/otp_src_${ERLANG_OTP} && \
    ./configure --without-javac --disable-hipe --enable-builtin-zlib --without-odbc --without-wx --prefix=${SRC}/erlang && \
    make -j$(nproc) && \
    make install && \
    rm -rf ${SRC}/erlang_build

ENV PATH="${SRC}/erlang/bin:${PATH}"

###################### end erlang #####################################################

#################### start elixir ########################################################
# Elixir 1.18.1
ARG ELIXIR_VERSION=1.18.1

RUN cd ${SRC} && wget https://github.com/elixir-lang/elixir/archive/refs/tags/v${ELIXIR_VERSION}.tar.gz && \
    tar xzvf v${ELIXIR_VERSION}.tar.gz && \
    cd elixir-${ELIXIR_VERSION} && \
    make -j$(nproc) && \
    make install PREFIX="${SRC}/elixir" && \
    cd ${SRC} && rm -rf elixir-${ELIXIR_VERSION} v${ELIXIR_VERSION}.tar.gz

ENV PATH="${SRC}/elixir/bin:${PATH}"

# Install IElixir (Jupyter kernel for Elixir)
RUN cd ${SRC} && curl -L https://github.com/pprzetacznik/IElixir/archive/refs/heads/master.zip -o ielixir.zip \
    && unzip ielixir.zip \
    && mv IElixir-master ielixir \
    && rm ielixir.zip \
    && cd ielixir \
    && mix local.hex --force \
    && mix local.rebar --force \
    && mix deps.get \
    && mix deps.compile \
    && ./install_script.sh

#################### end elixir ########################################################

EXPOSE 8888

CMD jupyter lab --ip 0.0.0.0 --no-browser --NotebookApp.token='' --NotebookApp.password='' --notebook-dir="$HOME/note"
